car=('engine','battery','alternator','ratiator','steering','break','seatbelt')
print("Components of a car:",car)
print("first element:",car[0])
print("fourth element of car:",car[3])
print("component of car from 0 to 4 index",car[0:5])
print("5th or -2th element:",car[-2])
print("index of alternator",car.index('alternator'))
print("Length of elements in car tuple : ",len(car))
